In [1]:
import requests
from requests import get
import numpy as np
import pandas as pd
import time

In [62]:
page_link='https://kino.mail.ru/awards/oscar/nomination/5/'
response=get(page_link)
response
from selenium import webdriver
driver = webdriver.Chrome('./chromedriver.exe')
ref='https://kino.mail.ru/awards/oscar/nomination/5/'
driver.get(ref)
from bs4 import BeautifulSoup
soup=BeautifulSoup(driver.page_source)

C:\Users\Олеся Щербакова\AppData\Local\Temp\ipykernel_21132\4129326004.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('./chromedriver.exe')

In [63]:
names=soup.find_all('a', {'class': 'link-holder'})
names_list=list(names)
df_names = pd.DataFrame(names_list)
df_names

                                      0
0                        Дэниэл Шайнерт
1                     Все везде и сразу
2                              Дэн Кван
3                     Все везде и сразу
4                         Джейн Кэмпион
5                            Власть пса
6                             Хлоя Чжао
7                      Земля кочевников
8                           Пон Джун-хо
9                              Паразиты
10                      Альфонсо Куарон
11                                 Рома
12                   Гильермо дель Торо
13                           Форма воды
14                        Дэмьен Шазелл
15                           Ла-Ла Ленд
16         Алехандро Гонсалес Иньярриту
17                             Выживший
18         Алехандро Гонсалес Иньярриту
19                              Бердмэн
20                      Альфонсо Куарон
21                           Гравитация
22                               Энг Ли
23                             Жизнь Пи
24                   Мишель Хазанавичус
25                               Артист
26                            Том Хупер
27                      Король говорит!
28                       Кэтрин Бигелоу
29                      Повелитель бури
30                           Дэнни Бойл
31                  Миллионер из трущоб
32                            Итан Коэн
33                Старикам тут не место
34                           Джоэл Коэн
35                Старикам тут не место
36                      Мартин Скорсезе
37                           Отступники
38                               Энг Ли
39                        Горбатая гора
40                         Клинт Иствуд
41                   Малышка на миллион
42                        Питер Джексон
43  Властелин колец: Возвращение короля
44                       Роман Полански
45                              Пианист
46                           Рон Ховард
47                          Игры разума
48                     Стивен Содерберг
49                              Траффик
50                           Сэм Мендес
51               Красота по-американски
52                      Стивен Спилберг
53               Спасти рядового Райана

In [73]:
page_link2='https://kino.mail.ru/awards/oscar/nomination/5/?page=2'
response2=get(page_link2)
response2
from selenium import webdriver
driver2 = webdriver.Chrome('./chromedriver.exe')
ref2='https://kino.mail.ru/awards/oscar/nomination/5/?page=2'
driver2.get(ref2)
from bs4 import BeautifulSoup
soup2=BeautifulSoup(driver2.page_source)

C:\Users\Олеся Щербакова\AppData\Local\Temp\ipykernel_21132\2922928525.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver2 = webdriver.Chrome('./chromedriver.exe')

In [65]:
names2=soup2.find_all('a', {'class': 'link-holder'})
names_list2=list(names2)
df_names2 = pd.DataFrame(names_list2)
df_names2

                               0
0                 Джеймс Кэмерон
1                        Титаник
2                Энтони Мингелла
3             Английский пациент
4                     Мэл Гибсон
5                 Храброе сердце
6                 Роберт Земекис
7                   Форрест Гамп
8                Стивен Спилберг
9                Список Шиндлера
10                  Клинт Иствуд
11                   Непрощенный
12                Джонатан Демме
13                Молчание ягнят
14                 Кевин Костнер
15           Танцующий с волками
16                  Оливер Стоун
17     Рожденный четвертого июля
18                Барри Левинсон
19                 Человек дождя
20           Бернардо Бертолуччи
21           Последний император
22                  Оливер Стоун
23                         Взвод
24                  Сидни Поллак
25                     Из Африки
26                  Милош Форман
27                        Амадей
28               Джеймс Л. Брукс
29                 Язык нежности
30              Ричард Аттенборо
31                         Ганди
32                  Уоррен Битти
33                       Красные
34                Роберт Редфорд
35             Обыкновенные люди
36                 Роберт Бентон
37         Крамер против Крамера
38                  Майкл Чимино
39             Охотник на оленей
40                    Вуди Аллен
41                     Энни Холл
42              Джон Г. Эвилдсен
43                         Рокки
44                  Милош Форман
45  Пролетая над гнездом кукушки
46          Френсис Форд Коппола
47               Крестный отец 2
48               Джордж Рой Хилл
49                         Афера

In [68]:
page_link3='https://kino.mail.ru/awards/oscar/nomination/5/?page=3'
response3=get(page_link3)
response3
from selenium import webdriver
driver3 = webdriver.Chrome('./chromedriver.exe')
ref3='https://kino.mail.ru/awards/oscar/nomination/5/?page=3'
driver3.get(ref3)
from bs4 import BeautifulSoup
soup3=BeautifulSoup(driver3.page_source)

C:\Users\Олеся Щербакова\AppData\Local\Temp\ipykernel_21132\449552715.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver3 = webdriver.Chrome('./chromedriver.exe')

In [69]:
names3=soup3.find_all('a', {'class': 'link-holder'})
names_list3=list(names3)
df_names3 = pd.DataFrame(names_list3)
df_names3

                         0
0                Боб Фосси
1                   Кабаре
2           Уильям Фридкин
3      Французский связной
4     Франклин Дж. Шаффнер
5                   Паттон
6           Джон Шлезингер
7        Полуночный ковбой
8                Кэрол Рид
9                  Оливер!
10             Майк Николс
11               Выпускник
12           Фред Циннеман
13  Человек на все времена
14             Роберт Уайз
15            Звуки музыки
16           Джордж Кьюкор
17     Моя прекрасная леди
18          Тони Ричардсон
19               Том Джонс
20               Дэвид Лин
21      Лоуренс Аравийский
22             Роберт Уайз
23    Вестсайдская история
24          Джером Роббинс
25    Вестсайдская история
26           Билли Уайлдер
27                Квартира
28           Уильям Уайлер
29                 Бен-Гур
30       Винсенте Миннелли
31                    Жижи
32               Дэвид Лин
33    Мост через реку Квай
34          Джордж Стивенс
35                  Гигант
36            Делберт Манн
37                   Марти
38              Элиа Казан
39                 В порту
40           Фред Циннеман
41  Отныне и во веки веков
42               Джон Форд
43           Тихий человек
44          Джордж Стивенс
45       Место под солнцем
46     Джозеф Лео Манкевич
47               Все о Еве
48     Джозеф Лео Манкевич
49       Письмо трем женам
50            Джон Хьюстон
51  Сокровища Сьерра Мадре

In [71]:
resultm = pd.concat([df_names, df_names2, df_names3], axis=0)
resultm
dfm = resultm.drop(resultm.index[1::2])
dfm

                      0
0        Дэниэл Шайнерт
2              Дэн Кван
4         Джейн Кэмпион
6             Хлоя Чжао
8           Пон Джун-хо
..                  ...
42            Джон Форд
44       Джордж Стивенс
46  Джозеф Лео Манкевич
48  Джозеф Лео Манкевич
50         Джон Хьюстон

[78 rows x 1 columns]

In [44]:
dfm.to_csv('actresssoscar.csv')
import os
print(os.getcwd())

C:\Users\Олеся Щербакова

In [45]:
dfm.to_pickle('actresssoscar.pkl')
import os
print(os.getcwd())

C:\Users\Олеся Щербакова

In [35]:
hg=pd.read_csv('actorsoscat.csv')
hg

    Unnamed: 0                  0
0            0    Брендан Фрейзер
1            2          Уилл Смит
2            4     Энтони Хопкинс
3            6      Хоакин Феникс
4            8         Рами Малек
..         ...                ...
70          40         Гэри Купер
71          42      Хамфри Богарт
72          44        Хосе Феррер
73          46  Бродерик Кроуфорд
74          48     Лоуренс Оливье

[75 rows x 2 columns]

In [47]:
fem=pd.read_csv('actresssoscar.csv')
fem

    Unnamed: 0                    0
0            0           Мишель Йео
1            2     Джессика Честейн
2            4   Фрэнсис МакДорманд
3            6       Рене Зеллвегер
4            8        Оливия Колман
..         ...                  ...
71          42            Ширли Бут
72          44            Вивьен Ли
73          46       Джуди Холлидэй
74          48  Оливия Де Хэвилленд
75          50         Джейн Уаймен

[76 rows x 2 columns]

In [50]:
akteri=pd.concat([hg, fem], axis=0)
akteri.reset_index(drop= True)
akteri

    Unnamed: 0                    0
0            0      Брендан Фрейзер
1            2            Уилл Смит
2            4       Энтони Хопкинс
3            6        Хоакин Феникс
4            8           Рами Малек
..         ...                  ...
71          42            Ширли Бут
72          44            Вивьен Ли
73          46       Джуди Холлидэй
74          48  Оливия Де Хэвилленд
75          50         Джейн Уаймен

[151 rows x 2 columns]

In [56]:
#akteri = akteri.drop('Unnamed: 0', axis=1)
akteri
akteri.reset_index(drop= True)
akteri

                      0
0       Брендан Фрейзер
1             Уилл Смит
2        Энтони Хопкинс
3         Хоакин Феникс
4            Рами Малек
..                  ...
71            Ширли Бут
72            Вивьен Ли
73       Джуди Холлидэй
74  Оливия Де Хэвилленд
75         Джейн Уаймен

[151 rows x 1 columns]

In [59]:
kkk=akteri.reset_index(drop= True)
kkk

                       0
0        Брендан Фрейзер
1              Уилл Смит
2         Энтони Хопкинс
3          Хоакин Феникс
4             Рами Малек
..                   ...
146            Ширли Бут
147            Вивьен Ли
148       Джуди Холлидэй
149  Оливия Де Хэвилленд
150         Джейн Уаймен

[151 rows x 1 columns]

In [61]:
ppp=kkk.values.tolist()
ppp

[['Брендан Фрейзер'],
 ['Уилл Смит'],
 ['Энтони Хопкинс'],
 ['Хоакин Феникс'],
 ['Рами Малек'],
 ['Гари Олдман'],
 ['Кейси Аффлек'],
 ['Леонардо ДиКаприо'],
 ['Эдди Редмэйн'],
 ['Мэттью Макконахи'],
 ['Дэниэл Дэй-Льюис'],
 ['Жан Дюжарден'],
 ['Колин Ферт'],
 ['Джефф Бриджес'],
 ['Шон Пенн'],
 ['Дэниэл Дэй-Льюис'],
 ['Форест Уитакер'],
 ['Филип Сеймур Хоффман'],
 ['Джейми Фокс'],
 ['Шон Пенн'],
 ['Эдриан Броуди'],
 ['Дензел Вашингтон'],
 ['Рассел Кроу'],
 ['Кевин Спейси'],
 ['Роберто Бениньи'],
 ['Джек Николсон'],
 ['Джеффри Раш'],
 ['Николас Кейдж'],
 ['Том Хэнкс'],
 ['Том Хэнкс'],
 ['Аль Пачино'],
 ['Энтони Хопкинс'],
 ['Джереми Айронс'],
 ['Дэниэл Дэй-Льюис'],
 ['Дастин Хоффман'],
 ['Майкл Дуглас'],
 ['Пол Ньюман'],
 ['Уильям Херт'],
 ['Ф. Мюррэй Абрахам'],
 ['Роберт Дювалл'],
 ['Бен Кингсли'],
 ['Генри Фонда'],
 ['Роберт Де Ниро'],
 ['Дастин Хоффман'],
 ['Джон Войт'],
 ['Ричард Дрейфусс'],
 ['Питер Финч'],
 ['Джек Николсон'],
 ['Арт Карни'],
 ['Джек Леммон'],
 ['Марлон Брандо'],
 ['Джин Хэкмен'],
 ['Джордж К. Скотт'],
 ['Джон Уэйн'],
 ['Клифф Робертсон'],
 ['Род Стайгер'],
 ['Пол Скофилд'],
 ['Ли Марвин'],
 ['Рекс Харрисон'],
 ['Сидни Пуатье'],
 ['Грегори Пек'],
 ['Максимилиан Шелл'],
 ['Берт Ланкастер'],
 ['Чарлтон Хестон'],
 ['Дэвид Нивен'],
 ['Алек Гиннесс'],
 ['Юл Бриннер'],
 ['Эрнест Боргнайн'],
 ['Марлон Брандо'],
 ['Уильям Холден'],
 ['Гэри Купер'],
 ['Хамфри Богарт'],
 ['Хосе Феррер'],
 ['Бродерик Кроуфорд'],
 ['Лоуренс Оливье'],
 ['Мишель Йео'],
 ['Джессика Честейн'],
 ['Фрэнсис МакДорманд'],
 ['Рене Зеллвегер'],
 ['Оливия Колман'],
 ['Фрэнсис МакДорманд'],
 ['Эмма Стоун'],
 ['Бри Ларсон'],
 ['Джулианна Мур'],
 ['Кейт Бланшетт'],
 ['Дженнифер Лоуренс'],
 ['Мэрил Стрип'],
 ['Натали Портман'],
 ['Сандра Буллок'],
 ['Кейт Уинслет'],
 ['Марион Котийяр'],
 ['Хелен Миррен'],
 ['Риз Уизерспун'],
 ['Хилари Суэнк'],
 ['Шарлиз Терон'],
 ['Николь Кидман'],
 ['Холли Берри'],
 ['Джулия Робертс'],
 ['Хилари Суэнк'],
 ['Гвинет Пэлтроу'],
 ['Хелен Хант'],
 ['Фрэнсис МакДорманд'],
 ['Сьюзен Сарандон'],
 ['Джессика Лэнг'],
 ['Холли Хантер'],
 ['Эмма Томпсон'],
 ['Джоди Фостер'],
 ['Кэти Бейтс'],
 ['Джессика Тэнди'],
 ['Джоди Фостер'],
 ['Шер'],
 ['Марли Мэтлин'],
 ['Джеральдин Пейдж'],
 ['Салли Филд'],
 ['Ширли МакЛейн'],
 ['Мэрил Стрип'],
 ['Кэтрин Хепберн'],
 ['Сисси Спейсек'],
 ['Салли Филд'],
 ['Джейн Фонда'],
 ['Дайан Китон'],
 ['Фэй Данауэй'],
 ['Луиза Флетчер'],
 ['Эллен Берстин'],
 ['Гленда Джексон'],
 ['Лайза Миннелли'],
 ['Джейн Фонда'],
 ['Гленда Джексон'],
 ['Мэгги Смит'],
 ['Барбра Стрейзанд'],
 ['Кэтрин Хепберн'],
 ['Кэтрин Хепберн'],
 ['Элизабет Тейлор'],
 ['Джули Кристи'],
 ['Джули Эндрюс'],
 ['Патриция Нил'],
 ['Энн Бэнкрофт'],
 ['Софи Лорен'],
 ['Элизабет Тейлор'],
 ['Симона Синьоре'],
 ['Сьюзен Хэйуорд'],
 ['Джоэнн Вудворд'],
 ['Ингрид Бергман'],
 ['Анна Маньяни'],
 ['Грейс Келли'],
 ['Одри Хепберн'],
 ['Ширли Бут'],
 ['Вивьен Ли'],
 ['Джуди Холлидэй'],
 ['Оливия Де Хэвилленд'],
 ['Джейн Уаймен']]

In [72]:
directors=dfm.values.tolist()
directors

[['Дэниэл Шайнерт'],
 ['Дэн Кван'],
 ['Джейн Кэмпион'],
 ['Хлоя Чжао'],
 ['Пон Джун-хо'],
 ['Альфонсо Куарон'],
 ['Гильермо дель Торо'],
 ['Дэмьен Шазелл'],
 ['Алехандро Гонсалес Иньярриту'],
 ['Алехандро Гонсалес Иньярриту'],
 ['Альфонсо Куарон'],
 ['Энг Ли'],
 ['Мишель Хазанавичус'],
 ['Том Хупер'],
 ['Кэтрин Бигелоу'],
 ['Дэнни Бойл'],
 ['Итан Коэн'],
 ['Джоэл Коэн'],
 ['Мартин Скорсезе'],
 ['Энг Ли'],
 ['Клинт Иствуд'],
 ['Питер Джексон'],
 ['Роман Полански'],
 ['Рон Ховард'],
 ['Стивен Содерберг'],
 ['Сэм Мендес'],
 ['Стивен Спилберг'],
 ['Джеймс Кэмерон'],
 ['Энтони Мингелла'],
 ['Мэл Гибсон'],
 ['Роберт Земекис'],
 ['Стивен Спилберг'],
 ['Клинт Иствуд'],
 ['Джонатан Демме'],
 ['Кевин Костнер'],
 ['Оливер Стоун'],
 ['Барри Левинсон'],
 ['Бернардо Бертолуччи'],
 ['Оливер Стоун'],
 ['Сидни Поллак'],
 ['Милош Форман'],
 ['Джеймс Л. Брукс'],
 ['Ричард Аттенборо'],
 ['Уоррен Битти'],
 ['Роберт Редфорд'],
 ['Роберт Бентон'],
 ['Майкл Чимино'],
 ['Вуди Аллен'],
 ['Джон Г. Эвилдсен'],
 ['Милош Форман'],
 ['Френсис Форд Коппола'],
 ['Джордж Рой Хилл'],
 ['Боб Фосси'],
 ['Уильям Фридкин'],
 ['Франклин Дж. Шаффнер'],
 ['Джон Шлезингер'],
 ['Кэрол Рид'],
 ['Майк Николс'],
 ['Фред Циннеман'],
 ['Роберт Уайз'],
 ['Джордж Кьюкор'],
 ['Тони Ричардсон'],
 ['Дэвид Лин'],
 ['Роберт Уайз'],
 ['Джером Роббинс'],
 ['Билли Уайлдер'],
 ['Уильям Уайлер'],
 ['Винсенте Миннелли'],
 ['Дэвид Лин'],
 ['Джордж Стивенс'],
 ['Делберт Манн'],
 ['Элиа Казан'],
 ['Фред Циннеман'],
 ['Джон Форд'],
 ['Джордж Стивенс'],
 ['Джозеф Лео Манкевич'],
 ['Джозеф Лео Манкевич'],
 ['Джон Хьюстон']]